name: run project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and Run Program
        run: |
          python -m pip install --upgrade pip
          pip install pipenv 
          pip install lxml
          pip3 install requests
          pipenv install
          pipenv run python3 main.py
